# Generated by Django 4.2.10 on 2024-02-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetmanage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmanage',
            name='image_url',
        ),
    ]
