# Generated by Django 4.2.10 on 2024-02-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_remove_assetmanage_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmanage',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='assetmanage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='asset.assetmanage')),
            ],
        ),
    ]
