# Generated by Django 4.2.10 on 2024-02-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_assetmanage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmanage',
            old_name='asset_coade',
            new_name='asset_code',
        ),
    ]
